# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.client_response import ClientResponse
from ..types.client_status_enum import ClientStatusEnum
from ..types.loan_response_with_installments import LoanResponseWithInstallments
from ..types.loan_status_enum import LoanStatusEnum
from ..types.webhook_event_type_enum import WebhookEventTypeEnum
from .raw_client import AsyncRawSandboxClient, RawSandboxClient
from .types.client_update_sandbox_limit import ClientUpdateSandboxLimit

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SandboxClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSandboxClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSandboxClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSandboxClient
        """
        return self._raw_client

    def update_client(
        self,
        client_id: str,
        *,
        status: typing.Optional[ClientStatusEnum] = OMIT,
        limit: typing.Optional[ClientUpdateSandboxLimit] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ClientResponse:
        """
        Update an existing client's status or credit limit using their client ID.

        Parameters
        ----------
        client_id : str

        status : typing.Optional[ClientStatusEnum]
            The status of the client. One of the following: `active, rejected, deactivated, pending, pending_onboarding, pre_approved, deleted, inactive`

        limit : typing.Optional[ClientUpdateSandboxLimit]
            The limit to set for the client. This will override the existing limit.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ClientResponse
            Successful Response

        Examples
        --------
        from voltaria import Voltaria

        client = Voltaria(
            api_key="YOUR_API_KEY",
        )
        client.sandbox.update_client(
            client_id="client_id",
        )
        """
        _response = self._raw_client.update_client(
            client_id, status=status, limit=limit, request_options=request_options
        )
        return _response.data

    def update_loan(
        self,
        loan_id: str,
        *,
        status: typing.Optional[LoanStatusEnum] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LoanResponseWithInstallments:
        """
        Update the status of a specific loan using its unique loan ID.

        Parameters
        ----------
        loan_id : str

        status : typing.Optional[LoanStatusEnum]
            The status of the client. One of the following: `pending, overdue, active, default, sold, restructured, repaid, pre_approved, rejected, deleted, inactive`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LoanResponseWithInstallments
            Successful Response

        Examples
        --------
        from voltaria import Voltaria

        client = Voltaria(
            api_key="YOUR_API_KEY",
        )
        client.sandbox.update_loan(
            loan_id="loan_id",
        )
        """
        _response = self._raw_client.update_loan(loan_id, status=status, request_options=request_options)
        return _response.data

    def webhook_test(
        self,
        *,
        event_type: WebhookEventTypeEnum,
        webhook_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Test a webhook subscription by ID or trigger all by event type.

        Parameters
        ----------
        event_type : WebhookEventTypeEnum
            Event type to trigger for the test. All subscriptions for this event type will be triggered if webhook_id is not provided.Possible values: loan_updated, installment_updated, client_updated, client_limit_updated, partner_limit_updated

        webhook_id : typing.Optional[str]
            The ID of the webhook subscription. Only this webhook will be triggered if provided.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Webhook test triggered successfully

        Examples
        --------
        from voltaria import Voltaria

        client = Voltaria(
            api_key="YOUR_API_KEY",
        )
        client.sandbox.webhook_test(
            event_type="loan.updated",
        )
        """
        _response = self._raw_client.webhook_test(
            event_type=event_type, webhook_id=webhook_id, request_options=request_options
        )
        return _response.data


class AsyncSandboxClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSandboxClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSandboxClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSandboxClient
        """
        return self._raw_client

    async def update_client(
        self,
        client_id: str,
        *,
        status: typing.Optional[ClientStatusEnum] = OMIT,
        limit: typing.Optional[ClientUpdateSandboxLimit] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ClientResponse:
        """
        Update an existing client's status or credit limit using their client ID.

        Parameters
        ----------
        client_id : str

        status : typing.Optional[ClientStatusEnum]
            The status of the client. One of the following: `active, rejected, deactivated, pending, pending_onboarding, pre_approved, deleted, inactive`

        limit : typing.Optional[ClientUpdateSandboxLimit]
            The limit to set for the client. This will override the existing limit.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ClientResponse
            Successful Response

        Examples
        --------
        import asyncio

        from voltaria import AsyncVoltaria

        client = AsyncVoltaria(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandbox.update_client(
                client_id="client_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_client(
            client_id, status=status, limit=limit, request_options=request_options
        )
        return _response.data

    async def update_loan(
        self,
        loan_id: str,
        *,
        status: typing.Optional[LoanStatusEnum] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LoanResponseWithInstallments:
        """
        Update the status of a specific loan using its unique loan ID.

        Parameters
        ----------
        loan_id : str

        status : typing.Optional[LoanStatusEnum]
            The status of the client. One of the following: `pending, overdue, active, default, sold, restructured, repaid, pre_approved, rejected, deleted, inactive`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LoanResponseWithInstallments
            Successful Response

        Examples
        --------
        import asyncio

        from voltaria import AsyncVoltaria

        client = AsyncVoltaria(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandbox.update_loan(
                loan_id="loan_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_loan(loan_id, status=status, request_options=request_options)
        return _response.data

    async def webhook_test(
        self,
        *,
        event_type: WebhookEventTypeEnum,
        webhook_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Test a webhook subscription by ID or trigger all by event type.

        Parameters
        ----------
        event_type : WebhookEventTypeEnum
            Event type to trigger for the test. All subscriptions for this event type will be triggered if webhook_id is not provided.Possible values: loan_updated, installment_updated, client_updated, client_limit_updated, partner_limit_updated

        webhook_id : typing.Optional[str]
            The ID of the webhook subscription. Only this webhook will be triggered if provided.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Webhook test triggered successfully

        Examples
        --------
        import asyncio

        from voltaria import AsyncVoltaria

        client = AsyncVoltaria(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandbox.webhook_test(
                event_type="loan.updated",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.webhook_test(
            event_type=event_type, webhook_id=webhook_id, request_options=request_options
        )
        return _response.data
