# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.bulk_loan_item_payload import BulkLoanItemPayload
from ..types.bulk_loan_task_response import BulkLoanTaskResponse
from ..types.bulk_loan_task_status import BulkLoanTaskStatus
from ..types.currency_enum import CurrencyEnum
from ..types.loan_installment_create_payload import LoanInstallmentCreatePayload
from ..types.loan_response_with_installments import LoanResponseWithInstallments
from ..types.paginated_response_loan_response_with_client_info import PaginatedResponseLoanResponseWithClientInfo
from .raw_client import AsyncRawLoansClient, RawLoansClient
from .types.loan_create_payload_amount import LoanCreatePayloadAmount
from .types.loan_default_payload_sold_amount import LoanDefaultPayloadSoldAmount

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class LoansClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawLoansClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawLoansClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawLoansClient
        """
        return self._raw_client

    def list_loans(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        client_id: typing.Optional[str] = None,
        order_by: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseLoanResponseWithClientInfo:
        """
        Retrieve all loans associated with your partner account. Supports optional filtering by client ID.

        Parameters
        ----------
        page : typing.Optional[int]

        page_size : typing.Optional[int]

        client_id : typing.Optional[str]

        order_by : typing.Optional[str]
            Field to order the results by, e.g., 'created_at:desc,updated_at:asc'

        q : typing.Optional[str]
            Query string for filtering. Format: "field:operator:value;...". Supported fields: id, client_id, status, client.name, correlation_id. Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseLoanResponseWithClientInfo
            Successful Response

        Examples
        --------
        from voltaria import Voltaria

        client = Voltaria(
            api_key="YOUR_API_KEY",
        )
        client.loans.list_loans()
        """
        _response = self._raw_client.list_loans(
            page=page, page_size=page_size, client_id=client_id, order_by=order_by, q=q, request_options=request_options
        )
        return _response.data

    def create_loan(
        self,
        *,
        client_id: str,
        currency: CurrencyEnum,
        amount: LoanCreatePayloadAmount,
        installments: typing.Sequence[LoanInstallmentCreatePayload],
        correlation_id: typing.Optional[str] = OMIT,
        loan_date: typing.Optional[dt.date] = OMIT,
        data: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LoanResponseWithInstallments:
        """
        Create a new loan for an approved client with an active credit limit.

        Parameters
        ----------
        client_id : str
            The ID of the client for this loan

        currency : CurrencyEnum
            The currency of the loan, must be one of the supported currencies: eur, gbp, usd, czk, pln, isk

        amount : LoanCreatePayloadAmount
            The amount of the loan

        installments : typing.Sequence[LoanInstallmentCreatePayload]
            List of installments for the loan, each with a due date and amount

        correlation_id : typing.Optional[str]
            The correlation ID you provided at the creation of the loan

        loan_date : typing.Optional[dt.date]
            Please provide the loan_date if it differs from the loan creation time (created_at). Otherwise, it will be automatically set.

        data : typing.Optional[typing.Dict[str, typing.Any]]
            Additional data related to the loan

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LoanResponseWithInstallments
            Successful Response

        Examples
        --------
        import datetime

        from voltaria import LoanInstallmentCreatePayload, Voltaria

        client = Voltaria(
            api_key="YOUR_API_KEY",
        )
        client.loans.create_loan(
            client_id="client_ACME",
            currency="eur",
            amount=1.1,
            installments=[
                LoanInstallmentCreatePayload(
                    expected_repayment_at=datetime.date.fromisoformat(
                        "2025-12-01",
                    ),
                    amount=1.1,
                )
            ],
        )
        """
        _response = self._raw_client.create_loan(
            client_id=client_id,
            currency=currency,
            amount=amount,
            installments=installments,
            correlation_id=correlation_id,
            loan_date=loan_date,
            data=data,
            request_options=request_options,
        )
        return _response.data

    def get_loan_by_id(
        self, loan_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> LoanResponseWithInstallments:
        """
        Retrieve detailed information about a specific loan by its loan ID.

        Parameters
        ----------
        loan_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LoanResponseWithInstallments
            Successful Response

        Examples
        --------
        from voltaria import Voltaria

        client = Voltaria(
            api_key="YOUR_API_KEY",
        )
        client.loans.get_loan_by_id(
            loan_id="loan_id",
        )
        """
        _response = self._raw_client.get_loan_by_id(loan_id, request_options=request_options)
        return _response.data

    def delete_loan(
        self, loan_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Dict[str, typing.Any]]:
        """
        Delete a loan by ID. Only loans with 'pending' status can be deleted.

        Parameters
        ----------
        loan_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Dict[str, typing.Any]]
            Successful Response

        Examples
        --------
        from voltaria import Voltaria

        client = Voltaria(
            api_key="YOUR_API_KEY",
        )
        client.loans.delete_loan(
            loan_id="loan_id",
        )
        """
        _response = self._raw_client.delete_loan(loan_id, request_options=request_options)
        return _response.data

    def create_bulk_loans(
        self, *, loans: typing.Sequence[BulkLoanItemPayload], request_options: typing.Optional[RequestOptions] = None
    ) -> BulkLoanTaskResponse:
        """
        Create multiple loans in a single request. Processing happens asynchronously. Returns a task ID for tracking progress.

        Parameters
        ----------
        loans : typing.Sequence[BulkLoanItemPayload]
            List of loans to create (max 1000)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BulkLoanTaskResponse
            Successful Response

        Examples
        --------
        import datetime

        from voltaria import (
            BulkLoanItemPayload,
            LoanInstallmentCreatePayload,
            Voltaria,
        )

        client = Voltaria(
            api_key="YOUR_API_KEY",
        )
        client.loans.create_bulk_loans(
            loans=[
                BulkLoanItemPayload(
                    client_id="client_123",
                    currency="eur",
                    amount="50000.00",
                    correlation_id="LOAN_001",
                    loan_date=datetime.date.fromisoformat(
                        "2023-05-01",
                    ),
                    installments=[
                        LoanInstallmentCreatePayload(
                            expected_repayment_at=datetime.date.fromisoformat(
                                "2023-06-01",
                            ),
                            amount="26000.00",
                        ),
                        LoanInstallmentCreatePayload(
                            expected_repayment_at=datetime.date.fromisoformat(
                                "2023-07-01",
                            ),
                            amount="26000.00",
                        ),
                    ],
                    data={"loan_type": "business", "purpose": "expansion"},
                )
            ],
        )
        """
        _response = self._raw_client.create_bulk_loans(loans=loans, request_options=request_options)
        return _response.data

    def get_bulk_loan_status(
        self, task_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BulkLoanTaskStatus:
        """
        Check the status of a bulk loan creation task and retrieve results when completed.

        Parameters
        ----------
        task_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BulkLoanTaskStatus
            Successful Response

        Examples
        --------
        from voltaria import Voltaria

        client = Voltaria(
            api_key="YOUR_API_KEY",
        )
        client.loans.get_bulk_loan_status(
            task_id="task_id",
        )
        """
        _response = self._raw_client.get_bulk_loan_status(task_id, request_options=request_options)
        return _response.data

    def set_loan_default(
        self,
        loan_id: str,
        *,
        default_date: dt.date,
        sold_amount: LoanDefaultPayloadSoldAmount,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LoanResponseWithInstallments:
        """
        Mark a loan as defaulted, recording the default date and the amount recovered from selling it. Defaults the loan's active and overdue installments and updates the loan status accordingly.

        Parameters
        ----------
        loan_id : str

        default_date : dt.date
            Date the loan is marked as defaulted.

        sold_amount : LoanDefaultPayloadSoldAmount
            Amount recovered when the defaulted loan is sold.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LoanResponseWithInstallments
            Successful Response

        Examples
        --------
        import datetime

        from voltaria import Voltaria

        client = Voltaria(
            api_key="YOUR_API_KEY",
        )
        client.loans.set_loan_default(
            loan_id="loan_id",
            default_date=datetime.date.fromisoformat(
                "2026-06-23",
            ),
            sold_amount=1.1,
        )
        """
        _response = self._raw_client.set_loan_default(
            loan_id, default_date=default_date, sold_amount=sold_amount, request_options=request_options
        )
        return _response.data


class AsyncLoansClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawLoansClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawLoansClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawLoansClient
        """
        return self._raw_client

    async def list_loans(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        client_id: typing.Optional[str] = None,
        order_by: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseLoanResponseWithClientInfo:
        """
        Retrieve all loans associated with your partner account. Supports optional filtering by client ID.

        Parameters
        ----------
        page : typing.Optional[int]

        page_size : typing.Optional[int]

        client_id : typing.Optional[str]

        order_by : typing.Optional[str]
            Field to order the results by, e.g., 'created_at:desc,updated_at:asc'

        q : typing.Optional[str]
            Query string for filtering. Format: "field:operator:value;...". Supported fields: id, client_id, status, client.name, correlation_id. Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseLoanResponseWithClientInfo
            Successful Response

        Examples
        --------
        import asyncio

        from voltaria import AsyncVoltaria

        client = AsyncVoltaria(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.loans.list_loans()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_loans(
            page=page, page_size=page_size, client_id=client_id, order_by=order_by, q=q, request_options=request_options
        )
        return _response.data

    async def create_loan(
        self,
        *,
        client_id: str,
        currency: CurrencyEnum,
        amount: LoanCreatePayloadAmount,
        installments: typing.Sequence[LoanInstallmentCreatePayload],
        correlation_id: typing.Optional[str] = OMIT,
        loan_date: typing.Optional[dt.date] = OMIT,
        data: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LoanResponseWithInstallments:
        """
        Create a new loan for an approved client with an active credit limit.

        Parameters
        ----------
        client_id : str
            The ID of the client for this loan

        currency : CurrencyEnum
            The currency of the loan, must be one of the supported currencies: eur, gbp, usd, czk, pln, isk

        amount : LoanCreatePayloadAmount
            The amount of the loan

        installments : typing.Sequence[LoanInstallmentCreatePayload]
            List of installments for the loan, each with a due date and amount

        correlation_id : typing.Optional[str]
            The correlation ID you provided at the creation of the loan

        loan_date : typing.Optional[dt.date]
            Please provide the loan_date if it differs from the loan creation time (created_at). Otherwise, it will be automatically set.

        data : typing.Optional[typing.Dict[str, typing.Any]]
            Additional data related to the loan

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LoanResponseWithInstallments
            Successful Response

        Examples
        --------
        import asyncio
        import datetime

        from voltaria import AsyncVoltaria, LoanInstallmentCreatePayload

        client = AsyncVoltaria(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.loans.create_loan(
                client_id="client_ACME",
                currency="eur",
                amount=1.1,
                installments=[
                    LoanInstallmentCreatePayload(
                        expected_repayment_at=datetime.date.fromisoformat(
                            "2025-12-01",
                        ),
                        amount=1.1,
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_loan(
            client_id=client_id,
            currency=currency,
            amount=amount,
            installments=installments,
            correlation_id=correlation_id,
            loan_date=loan_date,
            data=data,
            request_options=request_options,
        )
        return _response.data

    async def get_loan_by_id(
        self, loan_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> LoanResponseWithInstallments:
        """
        Retrieve detailed information about a specific loan by its loan ID.

        Parameters
        ----------
        loan_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LoanResponseWithInstallments
            Successful Response

        Examples
        --------
        import asyncio

        from voltaria import AsyncVoltaria

        client = AsyncVoltaria(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.loans.get_loan_by_id(
                loan_id="loan_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_loan_by_id(loan_id, request_options=request_options)
        return _response.data

    async def delete_loan(
        self, loan_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Dict[str, typing.Any]]:
        """
        Delete a loan by ID. Only loans with 'pending' status can be deleted.

        Parameters
        ----------
        loan_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Dict[str, typing.Any]]
            Successful Response

        Examples
        --------
        import asyncio

        from voltaria import AsyncVoltaria

        client = AsyncVoltaria(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.loans.delete_loan(
                loan_id="loan_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_loan(loan_id, request_options=request_options)
        return _response.data

    async def create_bulk_loans(
        self, *, loans: typing.Sequence[BulkLoanItemPayload], request_options: typing.Optional[RequestOptions] = None
    ) -> BulkLoanTaskResponse:
        """
        Create multiple loans in a single request. Processing happens asynchronously. Returns a task ID for tracking progress.

        Parameters
        ----------
        loans : typing.Sequence[BulkLoanItemPayload]
            List of loans to create (max 1000)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BulkLoanTaskResponse
            Successful Response

        Examples
        --------
        import asyncio
        import datetime

        from voltaria import (
            AsyncVoltaria,
            BulkLoanItemPayload,
            LoanInstallmentCreatePayload,
        )

        client = AsyncVoltaria(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.loans.create_bulk_loans(
                loans=[
                    BulkLoanItemPayload(
                        client_id="client_123",
                        currency="eur",
                        amount="50000.00",
                        correlation_id="LOAN_001",
                        loan_date=datetime.date.fromisoformat(
                            "2023-05-01",
                        ),
                        installments=[
                            LoanInstallmentCreatePayload(
                                expected_repayment_at=datetime.date.fromisoformat(
                                    "2023-06-01",
                                ),
                                amount="26000.00",
                            ),
                            LoanInstallmentCreatePayload(
                                expected_repayment_at=datetime.date.fromisoformat(
                                    "2023-07-01",
                                ),
                                amount="26000.00",
                            ),
                        ],
                        data={"loan_type": "business", "purpose": "expansion"},
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_bulk_loans(loans=loans, request_options=request_options)
        return _response.data

    async def get_bulk_loan_status(
        self, task_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BulkLoanTaskStatus:
        """
        Check the status of a bulk loan creation task and retrieve results when completed.

        Parameters
        ----------
        task_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BulkLoanTaskStatus
            Successful Response

        Examples
        --------
        import asyncio

        from voltaria import AsyncVoltaria

        client = AsyncVoltaria(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.loans.get_bulk_loan_status(
                task_id="task_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_bulk_loan_status(task_id, request_options=request_options)
        return _response.data

    async def set_loan_default(
        self,
        loan_id: str,
        *,
        default_date: dt.date,
        sold_amount: LoanDefaultPayloadSoldAmount,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> LoanResponseWithInstallments:
        """
        Mark a loan as defaulted, recording the default date and the amount recovered from selling it. Defaults the loan's active and overdue installments and updates the loan status accordingly.

        Parameters
        ----------
        loan_id : str

        default_date : dt.date
            Date the loan is marked as defaulted.

        sold_amount : LoanDefaultPayloadSoldAmount
            Amount recovered when the defaulted loan is sold.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LoanResponseWithInstallments
            Successful Response

        Examples
        --------
        import asyncio
        import datetime

        from voltaria import AsyncVoltaria

        client = AsyncVoltaria(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.loans.set_loan_default(
                loan_id="loan_id",
                default_date=datetime.date.fromisoformat(
                    "2026-06-23",
                ),
                sold_amount=1.1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.set_loan_default(
            loan_id, default_date=default_date, sold_amount=sold_amount, request_options=request_options
        )
        return _response.data
