# This file was auto-generated by Fern from our API Definition.

import typing

TaskPartnerStatusUpdatePayloadStatus = typing.Union[
    typing.Literal["active", "in_progress", "blocked", "done"], typing.Any
]
