# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import httpx
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.logging import LogConfig, Logger
from .environment import VoltariaEnvironment

if typing.TYPE_CHECKING:
    from .accounts.client import AccountsClient, AsyncAccountsClient
    from .clients.client import AsyncClientsClient, ClientsClient
    from .collections.client import AsyncCollectionsClient, CollectionsClient
    from .documents.client import AsyncDocumentsClient, DocumentsClient
    from .drawdowns.client import AsyncDrawdownsClient, DrawdownsClient
    from .installments.client import AsyncInstallmentsClient, InstallmentsClient
    from .investors.client import AsyncInvestorsClient, InvestorsClient
    from .loans.client import AsyncLoansClient, LoansClient
    from .partners.client import AsyncPartnersClient, PartnersClient
    from .repayments.client import AsyncRepaymentsClient, RepaymentsClient
    from .sandbox.client import AsyncSandboxClient, SandboxClient
    from .webhooks.client import AsyncWebhooksClient, WebhooksClient


class Voltaria:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : VoltariaEnvironment
        The environment to use for requests from the client. from .environment import VoltariaEnvironment



        Defaults to VoltariaEnvironment.SANDBOX



    token : typing.Union[str, typing.Callable[[], str]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    max_retries : typing.Optional[int]
        The default maximum number of retries for failed requests. Defaults to 2. Per-request `max_retries` in `request_options` takes precedence over this value.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from voltaria import Voltaria

    client = Voltaria(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: VoltariaEnvironment = VoltariaEnvironment.SANDBOX,
        token: typing.Union[str, typing.Callable[[], str]],
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        _defaulted_max_retries = max_retries if max_retries is not None else 2
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            token=token,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            max_retries=_defaulted_max_retries,
            logging=logging,
        )
        self._clients: typing.Optional[ClientsClient] = None
        self._sandbox: typing.Optional[SandboxClient] = None
        self._accounts: typing.Optional[AccountsClient] = None
        self._collections: typing.Optional[CollectionsClient] = None
        self._documents: typing.Optional[DocumentsClient] = None
        self._investors: typing.Optional[InvestorsClient] = None
        self._installments: typing.Optional[InstallmentsClient] = None
        self._loans: typing.Optional[LoansClient] = None
        self._partners: typing.Optional[PartnersClient] = None
        self._webhooks: typing.Optional[WebhooksClient] = None
        self._repayments: typing.Optional[RepaymentsClient] = None
        self._drawdowns: typing.Optional[DrawdownsClient] = None

    @property
    def clients(self):
        if self._clients is None:
            from .clients.client import ClientsClient  # noqa: E402

            self._clients = ClientsClient(client_wrapper=self._client_wrapper)
        return self._clients

    @property
    def sandbox(self):
        if self._sandbox is None:
            from .sandbox.client import SandboxClient  # noqa: E402

            self._sandbox = SandboxClient(client_wrapper=self._client_wrapper)
        return self._sandbox

    @property
    def accounts(self):
        if self._accounts is None:
            from .accounts.client import AccountsClient  # noqa: E402

            self._accounts = AccountsClient(client_wrapper=self._client_wrapper)
        return self._accounts

    @property
    def collections(self):
        if self._collections is None:
            from .collections.client import CollectionsClient  # noqa: E402

            self._collections = CollectionsClient(client_wrapper=self._client_wrapper)
        return self._collections

    @property
    def documents(self):
        if self._documents is None:
            from .documents.client import DocumentsClient  # noqa: E402

            self._documents = DocumentsClient(client_wrapper=self._client_wrapper)
        return self._documents

    @property
    def investors(self):
        if self._investors is None:
            from .investors.client import InvestorsClient  # noqa: E402

            self._investors = InvestorsClient(client_wrapper=self._client_wrapper)
        return self._investors

    @property
    def installments(self):
        if self._installments is None:
            from .installments.client import InstallmentsClient  # noqa: E402

            self._installments = InstallmentsClient(client_wrapper=self._client_wrapper)
        return self._installments

    @property
    def loans(self):
        if self._loans is None:
            from .loans.client import LoansClient  # noqa: E402

            self._loans = LoansClient(client_wrapper=self._client_wrapper)
        return self._loans

    @property
    def partners(self):
        if self._partners is None:
            from .partners.client import PartnersClient  # noqa: E402

            self._partners = PartnersClient(client_wrapper=self._client_wrapper)
        return self._partners

    @property
    def webhooks(self):
        if self._webhooks is None:
            from .webhooks.client import WebhooksClient  # noqa: E402

            self._webhooks = WebhooksClient(client_wrapper=self._client_wrapper)
        return self._webhooks

    @property
    def repayments(self):
        if self._repayments is None:
            from .repayments.client import RepaymentsClient  # noqa: E402

            self._repayments = RepaymentsClient(client_wrapper=self._client_wrapper)
        return self._repayments

    @property
    def drawdowns(self):
        if self._drawdowns is None:
            from .drawdowns.client import DrawdownsClient  # noqa: E402

            self._drawdowns = DrawdownsClient(client_wrapper=self._client_wrapper)
        return self._drawdowns


def _make_default_async_client(
    timeout: typing.Optional[float],
    follow_redirects: typing.Optional[bool],
) -> httpx.AsyncClient:
    try:
        import httpx_aiohttp  # type: ignore[import-not-found]
    except ImportError:
        pass
    else:
        if follow_redirects is not None:
            return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout, follow_redirects=follow_redirects)
        return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout)

    if follow_redirects is not None:
        return httpx.AsyncClient(timeout=timeout, follow_redirects=follow_redirects)
    return httpx.AsyncClient(timeout=timeout)


class AsyncVoltaria:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : VoltariaEnvironment
        The environment to use for requests from the client. from .environment import VoltariaEnvironment



        Defaults to VoltariaEnvironment.SANDBOX



    token : typing.Union[str, typing.Callable[[], str]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    async_token : typing.Optional[typing.Callable[[], typing.Awaitable[str]]]
        An async callable that returns a bearer token. Use this when token acquisition involves async I/O (e.g., refreshing tokens via an async HTTP client). When provided, this is used instead of the synchronous token for async requests.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    max_retries : typing.Optional[int]
        The default maximum number of retries for failed requests. Defaults to 2. Per-request `max_retries` in `request_options` takes precedence over this value.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from voltaria import AsyncVoltaria

    client = AsyncVoltaria(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: VoltariaEnvironment = VoltariaEnvironment.SANDBOX,
        token: typing.Union[str, typing.Callable[[], str]],
        headers: typing.Optional[typing.Dict[str, str]] = None,
        async_token: typing.Optional[typing.Callable[[], typing.Awaitable[str]]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        _defaulted_max_retries = max_retries if max_retries is not None else 2
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            token=token,
            headers=headers,
            async_token=async_token,
            httpx_client=httpx_client
            if httpx_client is not None
            else _make_default_async_client(timeout=_defaulted_timeout, follow_redirects=follow_redirects),
            timeout=_defaulted_timeout,
            max_retries=_defaulted_max_retries,
            logging=logging,
        )
        self._clients: typing.Optional[AsyncClientsClient] = None
        self._sandbox: typing.Optional[AsyncSandboxClient] = None
        self._accounts: typing.Optional[AsyncAccountsClient] = None
        self._collections: typing.Optional[AsyncCollectionsClient] = None
        self._documents: typing.Optional[AsyncDocumentsClient] = None
        self._investors: typing.Optional[AsyncInvestorsClient] = None
        self._installments: typing.Optional[AsyncInstallmentsClient] = None
        self._loans: typing.Optional[AsyncLoansClient] = None
        self._partners: typing.Optional[AsyncPartnersClient] = None
        self._webhooks: typing.Optional[AsyncWebhooksClient] = None
        self._repayments: typing.Optional[AsyncRepaymentsClient] = None
        self._drawdowns: typing.Optional[AsyncDrawdownsClient] = None

    @property
    def clients(self):
        if self._clients is None:
            from .clients.client import AsyncClientsClient  # noqa: E402

            self._clients = AsyncClientsClient(client_wrapper=self._client_wrapper)
        return self._clients

    @property
    def sandbox(self):
        if self._sandbox is None:
            from .sandbox.client import AsyncSandboxClient  # noqa: E402

            self._sandbox = AsyncSandboxClient(client_wrapper=self._client_wrapper)
        return self._sandbox

    @property
    def accounts(self):
        if self._accounts is None:
            from .accounts.client import AsyncAccountsClient  # noqa: E402

            self._accounts = AsyncAccountsClient(client_wrapper=self._client_wrapper)
        return self._accounts

    @property
    def collections(self):
        if self._collections is None:
            from .collections.client import AsyncCollectionsClient  # noqa: E402

            self._collections = AsyncCollectionsClient(client_wrapper=self._client_wrapper)
        return self._collections

    @property
    def documents(self):
        if self._documents is None:
            from .documents.client import AsyncDocumentsClient  # noqa: E402

            self._documents = AsyncDocumentsClient(client_wrapper=self._client_wrapper)
        return self._documents

    @property
    def investors(self):
        if self._investors is None:
            from .investors.client import AsyncInvestorsClient  # noqa: E402

            self._investors = AsyncInvestorsClient(client_wrapper=self._client_wrapper)
        return self._investors

    @property
    def installments(self):
        if self._installments is None:
            from .installments.client import AsyncInstallmentsClient  # noqa: E402

            self._installments = AsyncInstallmentsClient(client_wrapper=self._client_wrapper)
        return self._installments

    @property
    def loans(self):
        if self._loans is None:
            from .loans.client import AsyncLoansClient  # noqa: E402

            self._loans = AsyncLoansClient(client_wrapper=self._client_wrapper)
        return self._loans

    @property
    def partners(self):
        if self._partners is None:
            from .partners.client import AsyncPartnersClient  # noqa: E402

            self._partners = AsyncPartnersClient(client_wrapper=self._client_wrapper)
        return self._partners

    @property
    def webhooks(self):
        if self._webhooks is None:
            from .webhooks.client import AsyncWebhooksClient  # noqa: E402

            self._webhooks = AsyncWebhooksClient(client_wrapper=self._client_wrapper)
        return self._webhooks

    @property
    def repayments(self):
        if self._repayments is None:
            from .repayments.client import AsyncRepaymentsClient  # noqa: E402

            self._repayments = AsyncRepaymentsClient(client_wrapper=self._client_wrapper)
        return self._repayments

    @property
    def drawdowns(self):
        if self._drawdowns is None:
            from .drawdowns.client import AsyncDrawdownsClient  # noqa: E402

            self._drawdowns = AsyncDrawdownsClient(client_wrapper=self._client_wrapper)
        return self._drawdowns


def _get_base_url(*, base_url: typing.Optional[str] = None, environment: VoltariaEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
