# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.not_found_error import NotFoundError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.currency_enum import CurrencyEnum
from ..types.paginated_response_recovery_response import PaginatedResponseRecoveryResponse
from ..types.recovery_response import RecoveryResponse
from .types.recovery_create_payload_amount import RecoveryCreatePayloadAmount
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawRecoveriesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_recoveries(
        self,
        *,
        client_id: typing.Optional[str] = None,
        loan_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PaginatedResponseRecoveryResponse]:
        """
        Retrieve recoveries recorded against your loans. Supports filtering by client or loan.

        Parameters
        ----------
        client_id : typing.Optional[str]

        loan_id : typing.Optional[str]

        page : typing.Optional[int]

        page_size : typing.Optional[int]

        order_by : typing.Optional[str]
            Field to order the results by, e.g., 'created_at:desc,updated_at:asc'

        q : typing.Optional[str]
            Query string for filtering. Format: "field:operator:value;...". Supported fields: id, client_id, loan_id, currency, recovery_date, created_at. Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaginatedResponseRecoveryResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/recoveries",
            method="GET",
            params={
                "client_id": client_id,
                "loan_id": loan_id,
                "page": page,
                "page_size": page_size,
                "order_by": order_by,
                "q": q,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedResponseRecoveryResponse,
                    parse_obj_as(
                        type_=PaginatedResponseRecoveryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_recovery(
        self,
        *,
        loan_id: str,
        amount: RecoveryCreatePayloadAmount,
        currency: CurrencyEnum,
        recovery_date: dt.date,
        notes: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[RecoveryResponse]:
        """
        Record a new recovery against one of your loans.

        Parameters
        ----------
        loan_id : str
            The ID of the loan this recovery is associated with.

        amount : RecoveryCreatePayloadAmount
            The amount recovered (must be > 0).

        currency : CurrencyEnum
            The currency of the recovered amount, must be one of the supported currencies: eur, gbp, usd, czk, pln, isk

        recovery_date : dt.date
            The date the recovery was made.

        notes : typing.Optional[str]
            Optional notes about the recovery.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[RecoveryResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/recoveries",
            method="POST",
            json={
                "loan_id": loan_id,
                "amount": convert_and_respect_annotation_metadata(
                    object_=amount, annotation=RecoveryCreatePayloadAmount, direction="write"
                ),
                "currency": currency,
                "recovery_date": recovery_date,
                "notes": notes,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RecoveryResponse,
                    parse_obj_as(
                        type_=RecoveryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawRecoveriesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_recoveries(
        self,
        *,
        client_id: typing.Optional[str] = None,
        loan_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PaginatedResponseRecoveryResponse]:
        """
        Retrieve recoveries recorded against your loans. Supports filtering by client or loan.

        Parameters
        ----------
        client_id : typing.Optional[str]

        loan_id : typing.Optional[str]

        page : typing.Optional[int]

        page_size : typing.Optional[int]

        order_by : typing.Optional[str]
            Field to order the results by, e.g., 'created_at:desc,updated_at:asc'

        q : typing.Optional[str]
            Query string for filtering. Format: "field:operator:value;...". Supported fields: id, client_id, loan_id, currency, recovery_date, created_at. Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaginatedResponseRecoveryResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/recoveries",
            method="GET",
            params={
                "client_id": client_id,
                "loan_id": loan_id,
                "page": page,
                "page_size": page_size,
                "order_by": order_by,
                "q": q,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedResponseRecoveryResponse,
                    parse_obj_as(
                        type_=PaginatedResponseRecoveryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_recovery(
        self,
        *,
        loan_id: str,
        amount: RecoveryCreatePayloadAmount,
        currency: CurrencyEnum,
        recovery_date: dt.date,
        notes: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[RecoveryResponse]:
        """
        Record a new recovery against one of your loans.

        Parameters
        ----------
        loan_id : str
            The ID of the loan this recovery is associated with.

        amount : RecoveryCreatePayloadAmount
            The amount recovered (must be > 0).

        currency : CurrencyEnum
            The currency of the recovered amount, must be one of the supported currencies: eur, gbp, usd, czk, pln, isk

        recovery_date : dt.date
            The date the recovery was made.

        notes : typing.Optional[str]
            Optional notes about the recovery.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[RecoveryResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/recoveries",
            method="POST",
            json={
                "loan_id": loan_id,
                "amount": convert_and_respect_annotation_metadata(
                    object_=amount, annotation=RecoveryCreatePayloadAmount, direction="write"
                ),
                "currency": currency,
                "recovery_date": recovery_date,
                "notes": notes,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RecoveryResponse,
                    parse_obj_as(
                        type_=RecoveryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
