# This file was auto-generated by Fern from our API Definition.

import typing

from .. import core
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.available_document_categories_response import AvailableDocumentCategoriesResponse
from ..types.document_response import DocumentResponse
from ..types.paginated_response_document_response import PaginatedResponseDocumentResponse
from .raw_client import AsyncRawDocumentsClient, RawDocumentsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class DocumentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDocumentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDocumentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDocumentsClient
        """
        return self._raw_client

    def list_documents(
        self,
        *,
        client_id: typing.Optional[str] = None,
        loan_id: typing.Optional[str] = None,
        installment_id: typing.Optional[str] = None,
        waterfall_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseDocumentResponse:
        """
        Retrieve all documents linked to a client.

        Parameters
        ----------
        client_id : typing.Optional[str]

        loan_id : typing.Optional[str]

        installment_id : typing.Optional[str]

        waterfall_id : typing.Optional[str]

        page : typing.Optional[int]

        page_size : typing.Optional[int]

        order_by : typing.Optional[str]
            Field to order the results by, e.g., 'created_at:desc,updated_at:asc'

        q : typing.Optional[str]
            Query string for filtering. Format: "field:operator:value;...". Supported fields: id, client_id, loan_id, installment_id, waterfall_id, category, file_name, document_date, folder_path. Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseDocumentResponse
            Successful Response

        Examples
        --------
        from voltaria import Voltaria

        client = Voltaria(
            api_key="YOUR_API_KEY",
        )
        client.documents.list_documents()
        """
        _response = self._raw_client.list_documents(
            client_id=client_id,
            loan_id=loan_id,
            installment_id=installment_id,
            waterfall_id=waterfall_id,
            page=page,
            page_size=page_size,
            order_by=order_by,
            q=q,
            request_options=request_options,
        )
        return _response.data

    def upload_document(
        self,
        *,
        category: str,
        file_name: str,
        file: core.File,
        client_id: typing.Optional[str] = None,
        loan_id: typing.Optional[str] = None,
        installment_id: typing.Optional[str] = None,
        waterfall_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DocumentResponse:
        """
        Upload a new document related to a client or loan, such as financial statements or KYC files.

        Parameters
        ----------
        category : str
            The category of the document. Available options can be fetched from the available categories endpoint. '.../documents/available-categories'.

        file_name : str
            The name of the file

        file : core.File
            See core.File for more documentation

        client_id : typing.Optional[str]

        loan_id : typing.Optional[str]

        installment_id : typing.Optional[str]

        waterfall_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocumentResponse
            Successful Response

        Examples
        --------
        from voltaria import Voltaria

        client = Voltaria(
            api_key="YOUR_API_KEY",
        )
        client.documents.upload_document(
            category="category",
            file_name="file_name",
        )
        """
        _response = self._raw_client.upload_document(
            category=category,
            file_name=file_name,
            file=file,
            client_id=client_id,
            loan_id=loan_id,
            installment_id=installment_id,
            waterfall_id=waterfall_id,
            request_options=request_options,
        )
        return _response.data

    def get_available_document_categories(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AvailableDocumentCategoriesResponse:
        """
        Retrieve all available document categories.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AvailableDocumentCategoriesResponse
            Successful Response

        Examples
        --------
        from voltaria import Voltaria

        client = Voltaria(
            api_key="YOUR_API_KEY",
        )
        client.documents.get_available_document_categories()
        """
        _response = self._raw_client.get_available_document_categories(request_options=request_options)
        return _response.data

    def get_document_by_id(
        self, document_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DocumentResponse:
        """
        Retrieve details for a specific document using its document ID.

        Parameters
        ----------
        document_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocumentResponse
            Successful Response

        Examples
        --------
        from voltaria import Voltaria

        client = Voltaria(
            api_key="YOUR_API_KEY",
        )
        client.documents.get_document_by_id(
            document_id="document_id",
        )
        """
        _response = self._raw_client.get_document_by_id(document_id, request_options=request_options)
        return _response.data

    def delete_document(self, document_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete a specific document by using its document ID.

        Parameters
        ----------
        document_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from voltaria import Voltaria

        client = Voltaria(
            api_key="YOUR_API_KEY",
        )
        client.documents.delete_document(
            document_id="document_id",
        )
        """
        _response = self._raw_client.delete_document(document_id, request_options=request_options)
        return _response.data


class AsyncDocumentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDocumentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDocumentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDocumentsClient
        """
        return self._raw_client

    async def list_documents(
        self,
        *,
        client_id: typing.Optional[str] = None,
        loan_id: typing.Optional[str] = None,
        installment_id: typing.Optional[str] = None,
        waterfall_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseDocumentResponse:
        """
        Retrieve all documents linked to a client.

        Parameters
        ----------
        client_id : typing.Optional[str]

        loan_id : typing.Optional[str]

        installment_id : typing.Optional[str]

        waterfall_id : typing.Optional[str]

        page : typing.Optional[int]

        page_size : typing.Optional[int]

        order_by : typing.Optional[str]
            Field to order the results by, e.g., 'created_at:desc,updated_at:asc'

        q : typing.Optional[str]
            Query string for filtering. Format: "field:operator:value;...". Supported fields: id, client_id, loan_id, installment_id, waterfall_id, category, file_name, document_date, folder_path. Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseDocumentResponse
            Successful Response

        Examples
        --------
        import asyncio

        from voltaria import AsyncVoltaria

        client = AsyncVoltaria(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.documents.list_documents()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_documents(
            client_id=client_id,
            loan_id=loan_id,
            installment_id=installment_id,
            waterfall_id=waterfall_id,
            page=page,
            page_size=page_size,
            order_by=order_by,
            q=q,
            request_options=request_options,
        )
        return _response.data

    async def upload_document(
        self,
        *,
        category: str,
        file_name: str,
        file: core.File,
        client_id: typing.Optional[str] = None,
        loan_id: typing.Optional[str] = None,
        installment_id: typing.Optional[str] = None,
        waterfall_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DocumentResponse:
        """
        Upload a new document related to a client or loan, such as financial statements or KYC files.

        Parameters
        ----------
        category : str
            The category of the document. Available options can be fetched from the available categories endpoint. '.../documents/available-categories'.

        file_name : str
            The name of the file

        file : core.File
            See core.File for more documentation

        client_id : typing.Optional[str]

        loan_id : typing.Optional[str]

        installment_id : typing.Optional[str]

        waterfall_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocumentResponse
            Successful Response

        Examples
        --------
        import asyncio

        from voltaria import AsyncVoltaria

        client = AsyncVoltaria(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.documents.upload_document(
                category="category",
                file_name="file_name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.upload_document(
            category=category,
            file_name=file_name,
            file=file,
            client_id=client_id,
            loan_id=loan_id,
            installment_id=installment_id,
            waterfall_id=waterfall_id,
            request_options=request_options,
        )
        return _response.data

    async def get_available_document_categories(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AvailableDocumentCategoriesResponse:
        """
        Retrieve all available document categories.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AvailableDocumentCategoriesResponse
            Successful Response

        Examples
        --------
        import asyncio

        from voltaria import AsyncVoltaria

        client = AsyncVoltaria(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.documents.get_available_document_categories()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_available_document_categories(request_options=request_options)
        return _response.data

    async def get_document_by_id(
        self, document_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DocumentResponse:
        """
        Retrieve details for a specific document using its document ID.

        Parameters
        ----------
        document_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocumentResponse
            Successful Response

        Examples
        --------
        import asyncio

        from voltaria import AsyncVoltaria

        client = AsyncVoltaria(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.documents.get_document_by_id(
                document_id="document_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_document_by_id(document_id, request_options=request_options)
        return _response.data

    async def delete_document(
        self, document_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Delete a specific document by using its document ID.

        Parameters
        ----------
        document_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from voltaria import AsyncVoltaria

        client = AsyncVoltaria(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.documents.delete_document(
                document_id="document_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_document(document_id, request_options=request_options)
        return _response.data
