# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.drawdown_response import DrawdownResponse
from ..types.paginated_response_drawdown_checklist_response import PaginatedResponseDrawdownChecklistResponse
from ..types.paginated_response_drawdown_response import PaginatedResponseDrawdownResponse
from .raw_client import AsyncRawDrawdownsClient, RawDrawdownsClient
from .types.drawdown_create_payload_amount import DrawdownCreatePayloadAmount

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class DrawdownsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDrawdownsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDrawdownsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDrawdownsClient
        """
        return self._raw_client

    def list_drawdowns(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseDrawdownResponse:
        """
        Retrieve a list of drawdowns.

        Parameters
        ----------
        page : typing.Optional[int]

        page_size : typing.Optional[int]

        order_by : typing.Optional[str]
            Field to order the results by, e.g., 'created_at:desc,updated_at:asc'

        q : typing.Optional[str]
            Query string for filtering. Format: "field:operator:value;...". Supported fields: . Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseDrawdownResponse
            Successful Response

        Examples
        --------
        from voltaria import Voltaria

        client = Voltaria(
            api_key="YOUR_API_KEY",
        )
        client.drawdowns.list_drawdowns()
        """
        _response = self._raw_client.list_drawdowns(
            page=page, page_size=page_size, order_by=order_by, q=q, request_options=request_options
        )
        return _response.data

    def create_drawdown_request(
        self,
        *,
        amount: DrawdownCreatePayloadAmount,
        drawdown_date: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DrawdownResponse:
        """
        Create a new drawdown request.

        Parameters
        ----------
        amount : DrawdownCreatePayloadAmount
            The amount for the drawdown.

        drawdown_date : typing.Optional[dt.datetime]
            The date for the drawdown. If not provided, defaults to the current date and time.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DrawdownResponse
            Successful Response

        Examples
        --------
        from voltaria import Voltaria

        client = Voltaria(
            api_key="YOUR_API_KEY",
        )
        client.drawdowns.create_drawdown_request(
            amount=1.1,
        )
        """
        _response = self._raw_client.create_drawdown_request(
            amount=amount, drawdown_date=drawdown_date, request_options=request_options
        )
        return _response.data

    def list_drawdown_checklists(
        self,
        drawdown_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseDrawdownChecklistResponse:
        """
        Retrieve all checklist items for a specific drawdown

        Parameters
        ----------
        drawdown_id : str

        page : typing.Optional[int]

        page_size : typing.Optional[int]

        order_by : typing.Optional[str]
            Field to order the results by, e.g., 'created_at:desc,updated_at:asc'

        q : typing.Optional[str]
            Query string for filtering. Format: "field:operator:value;...". Supported fields: . Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseDrawdownChecklistResponse
            Successful Response

        Examples
        --------
        from voltaria import Voltaria

        client = Voltaria(
            api_key="YOUR_API_KEY",
        )
        client.drawdowns.list_drawdown_checklists(
            drawdown_id="drawdown_id",
        )
        """
        _response = self._raw_client.list_drawdown_checklists(
            drawdown_id, page=page, page_size=page_size, order_by=order_by, q=q, request_options=request_options
        )
        return _response.data


class AsyncDrawdownsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDrawdownsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDrawdownsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDrawdownsClient
        """
        return self._raw_client

    async def list_drawdowns(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseDrawdownResponse:
        """
        Retrieve a list of drawdowns.

        Parameters
        ----------
        page : typing.Optional[int]

        page_size : typing.Optional[int]

        order_by : typing.Optional[str]
            Field to order the results by, e.g., 'created_at:desc,updated_at:asc'

        q : typing.Optional[str]
            Query string for filtering. Format: "field:operator:value;...". Supported fields: . Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseDrawdownResponse
            Successful Response

        Examples
        --------
        import asyncio

        from voltaria import AsyncVoltaria

        client = AsyncVoltaria(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.drawdowns.list_drawdowns()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_drawdowns(
            page=page, page_size=page_size, order_by=order_by, q=q, request_options=request_options
        )
        return _response.data

    async def create_drawdown_request(
        self,
        *,
        amount: DrawdownCreatePayloadAmount,
        drawdown_date: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DrawdownResponse:
        """
        Create a new drawdown request.

        Parameters
        ----------
        amount : DrawdownCreatePayloadAmount
            The amount for the drawdown.

        drawdown_date : typing.Optional[dt.datetime]
            The date for the drawdown. If not provided, defaults to the current date and time.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DrawdownResponse
            Successful Response

        Examples
        --------
        import asyncio

        from voltaria import AsyncVoltaria

        client = AsyncVoltaria(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.drawdowns.create_drawdown_request(
                amount=1.1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_drawdown_request(
            amount=amount, drawdown_date=drawdown_date, request_options=request_options
        )
        return _response.data

    async def list_drawdown_checklists(
        self,
        drawdown_id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseDrawdownChecklistResponse:
        """
        Retrieve all checklist items for a specific drawdown

        Parameters
        ----------
        drawdown_id : str

        page : typing.Optional[int]

        page_size : typing.Optional[int]

        order_by : typing.Optional[str]
            Field to order the results by, e.g., 'created_at:desc,updated_at:asc'

        q : typing.Optional[str]
            Query string for filtering. Format: "field:operator:value;...". Supported fields: . Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseDrawdownChecklistResponse
            Successful Response

        Examples
        --------
        import asyncio

        from voltaria import AsyncVoltaria

        client = AsyncVoltaria(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.drawdowns.list_drawdown_checklists(
                drawdown_id="drawdown_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_drawdown_checklists(
            drawdown_id, page=page, page_size=page_size, order_by=order_by, q=q, request_options=request_options
        )
        return _response.data
