# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.bulk_repayment_item_payload import BulkRepaymentItemPayload
from ..types.bulk_repayment_task_response import BulkRepaymentTaskResponse
from ..types.bulk_repayment_task_status import BulkRepaymentTaskStatus
from ..types.paginated_response_repayment_response_with_client_info import (
    PaginatedResponseRepaymentResponseWithClientInfo,
)
from ..types.repayment_response import RepaymentResponse
from .types.repayment_create_payload_amount import RepaymentCreatePayloadAmount
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawRepaymentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_repayment_logs(
        self,
        *,
        client_id: typing.Optional[str] = None,
        loan_id: typing.Optional[str] = None,
        installment_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PaginatedResponseRepaymentResponseWithClientInfo]:
        """
        Retrieve all repayments made under your partner account. Supports filtering by client, loan, or installments.

        Parameters
        ----------
        client_id : typing.Optional[str]

        loan_id : typing.Optional[str]

        installment_id : typing.Optional[str]

        page : typing.Optional[int]

        page_size : typing.Optional[int]

        order_by : typing.Optional[str]
            Field to order the results by, e.g., 'created_at:desc,updated_at:asc'

        q : typing.Optional[str]
            Query string for filtering. Format: "field:operator:value;...". Supported fields: id, client_id, loan_id, installment_id, created_at, client.name, client.correlation_id. Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PaginatedResponseRepaymentResponseWithClientInfo]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/repayments",
            method="GET",
            params={
                "client_id": client_id,
                "loan_id": loan_id,
                "installment_id": installment_id,
                "page": page,
                "page_size": page_size,
                "order_by": order_by,
                "q": q,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedResponseRepaymentResponseWithClientInfo,
                    parse_obj_as(
                        type_=PaginatedResponseRepaymentResponseWithClientInfo,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_repayment(
        self,
        *,
        amount: RepaymentCreatePayloadAmount,
        installment_id: typing.Optional[str] = None,
        loan_id: typing.Optional[str] = None,
        correlation_id: typing.Optional[str] = None,
        repayment_date: typing.Optional[dt.datetime] = OMIT,
        data: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        is_early_settlement: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[RepaymentResponse]:
        """
        Create a new repayment log for an installment. Requires the installment ID, loan ID or loan correlation ID.

        Parameters
        ----------
        amount : RepaymentCreatePayloadAmount
            The amount of payment made for installment

        installment_id : typing.Optional[str]
            ID of the installment

        loan_id : typing.Optional[str]
            ID of the associated Loan

        correlation_id : typing.Optional[str]
            Correlation ID of associated loan

        repayment_date : typing.Optional[dt.datetime]
            Please provide the repayment_date if it differs from the time you log this repayment. Otherwise, it will be automatically set.

        data : typing.Optional[typing.Dict[str, typing.Any]]
            Additional metadata related to the repayment

        is_early_settlement : typing.Optional[bool]
            Indicates if this repayment is for early settlement

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[RepaymentResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/repayments",
            method="POST",
            params={
                "installment_id": installment_id,
                "loan_id": loan_id,
                "correlation_id": correlation_id,
            },
            json={
                "amount": convert_and_respect_annotation_metadata(
                    object_=amount, annotation=RepaymentCreatePayloadAmount, direction="write"
                ),
                "repayment_date": repayment_date,
                "data": data,
                "is_early_settlement": is_early_settlement,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RepaymentResponse,
                    parse_obj_as(
                        type_=RepaymentResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_bulk_repayments(
        self,
        *,
        repayments: typing.Sequence[BulkRepaymentItemPayload],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[BulkRepaymentTaskResponse]:
        """
        Initiate processing of up to 10000 repayment logs. Returns task_id for tracking progress.

        Parameters
        ----------
        repayments : typing.Sequence[BulkRepaymentItemPayload]
            List of repayments to create (max 10000)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[BulkRepaymentTaskResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/repayments/bulk",
            method="POST",
            json={
                "repayments": convert_and_respect_annotation_metadata(
                    object_=repayments, annotation=typing.Sequence[BulkRepaymentItemPayload], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BulkRepaymentTaskResponse,
                    parse_obj_as(
                        type_=BulkRepaymentTaskResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_bulk_repayment_status(
        self, task_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[BulkRepaymentTaskStatus]:
        """
        Check the progress and results of a bulk repayment processing task.

        Parameters
        ----------
        task_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[BulkRepaymentTaskStatus]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/repayments/bulk/{encode_path_param(task_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BulkRepaymentTaskStatus,
                    parse_obj_as(
                        type_=BulkRepaymentTaskStatus,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawRepaymentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_repayment_logs(
        self,
        *,
        client_id: typing.Optional[str] = None,
        loan_id: typing.Optional[str] = None,
        installment_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PaginatedResponseRepaymentResponseWithClientInfo]:
        """
        Retrieve all repayments made under your partner account. Supports filtering by client, loan, or installments.

        Parameters
        ----------
        client_id : typing.Optional[str]

        loan_id : typing.Optional[str]

        installment_id : typing.Optional[str]

        page : typing.Optional[int]

        page_size : typing.Optional[int]

        order_by : typing.Optional[str]
            Field to order the results by, e.g., 'created_at:desc,updated_at:asc'

        q : typing.Optional[str]
            Query string for filtering. Format: "field:operator:value;...". Supported fields: id, client_id, loan_id, installment_id, created_at, client.name, client.correlation_id. Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PaginatedResponseRepaymentResponseWithClientInfo]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/repayments",
            method="GET",
            params={
                "client_id": client_id,
                "loan_id": loan_id,
                "installment_id": installment_id,
                "page": page,
                "page_size": page_size,
                "order_by": order_by,
                "q": q,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PaginatedResponseRepaymentResponseWithClientInfo,
                    parse_obj_as(
                        type_=PaginatedResponseRepaymentResponseWithClientInfo,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_repayment(
        self,
        *,
        amount: RepaymentCreatePayloadAmount,
        installment_id: typing.Optional[str] = None,
        loan_id: typing.Optional[str] = None,
        correlation_id: typing.Optional[str] = None,
        repayment_date: typing.Optional[dt.datetime] = OMIT,
        data: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        is_early_settlement: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[RepaymentResponse]:
        """
        Create a new repayment log for an installment. Requires the installment ID, loan ID or loan correlation ID.

        Parameters
        ----------
        amount : RepaymentCreatePayloadAmount
            The amount of payment made for installment

        installment_id : typing.Optional[str]
            ID of the installment

        loan_id : typing.Optional[str]
            ID of the associated Loan

        correlation_id : typing.Optional[str]
            Correlation ID of associated loan

        repayment_date : typing.Optional[dt.datetime]
            Please provide the repayment_date if it differs from the time you log this repayment. Otherwise, it will be automatically set.

        data : typing.Optional[typing.Dict[str, typing.Any]]
            Additional metadata related to the repayment

        is_early_settlement : typing.Optional[bool]
            Indicates if this repayment is for early settlement

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[RepaymentResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/repayments",
            method="POST",
            params={
                "installment_id": installment_id,
                "loan_id": loan_id,
                "correlation_id": correlation_id,
            },
            json={
                "amount": convert_and_respect_annotation_metadata(
                    object_=amount, annotation=RepaymentCreatePayloadAmount, direction="write"
                ),
                "repayment_date": repayment_date,
                "data": data,
                "is_early_settlement": is_early_settlement,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RepaymentResponse,
                    parse_obj_as(
                        type_=RepaymentResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_bulk_repayments(
        self,
        *,
        repayments: typing.Sequence[BulkRepaymentItemPayload],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[BulkRepaymentTaskResponse]:
        """
        Initiate processing of up to 10000 repayment logs. Returns task_id for tracking progress.

        Parameters
        ----------
        repayments : typing.Sequence[BulkRepaymentItemPayload]
            List of repayments to create (max 10000)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[BulkRepaymentTaskResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/repayments/bulk",
            method="POST",
            json={
                "repayments": convert_and_respect_annotation_metadata(
                    object_=repayments, annotation=typing.Sequence[BulkRepaymentItemPayload], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BulkRepaymentTaskResponse,
                    parse_obj_as(
                        type_=BulkRepaymentTaskResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_bulk_repayment_status(
        self, task_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[BulkRepaymentTaskStatus]:
        """
        Check the progress and results of a bulk repayment processing task.

        Parameters
        ----------
        task_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[BulkRepaymentTaskStatus]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/repayments/bulk/{encode_path_param(task_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BulkRepaymentTaskStatus,
                    parse_obj_as(
                        type_=BulkRepaymentTaskStatus,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
