# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.collection_action_log_response import CollectionActionLogResponse
from ..types.collection_action_status_enum import CollectionActionStatusEnum
from ..types.collection_action_type_enum import CollectionActionTypeEnum
from ..types.paginated_response_collection_action_log_response import PaginatedResponseCollectionActionLogResponse
from ..types.paginated_response_collection_action_response import PaginatedResponseCollectionActionResponse
from .raw_client import AsyncRawCollectionsClient, RawCollectionsClient
from .types.collection_action_log_update_payload_status import CollectionActionLogUpdatePayloadStatus

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CollectionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCollectionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCollectionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCollectionsClient
        """
        return self._raw_client

    def list_collection_actions(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseCollectionActionResponse:
        """
        Retrieve all collection actions configured for your partner account.

        Parameters
        ----------
        page : typing.Optional[int]

        page_size : typing.Optional[int]

        order_by : typing.Optional[str]
            Field to order the results by, e.g., 'created_at:desc,updated_at:asc'

        q : typing.Optional[str]
            Query string for filtering. Format: "field:operator:value;...". Supported fields: id, name, action_type, is_active, timing. Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseCollectionActionResponse
            Successful Response

        Examples
        --------
        from voltaria import Voltaria

        client = Voltaria(
            api_key="YOUR_API_KEY",
        )
        client.collections.list_collection_actions()
        """
        _response = self._raw_client.list_collection_actions(
            page=page, page_size=page_size, order_by=order_by, q=q, request_options=request_options
        )
        return _response.data

    def list_collection_action_logs(
        self,
        *,
        client_id: typing.Optional[str] = None,
        loan_id: typing.Optional[str] = None,
        installment_id: typing.Optional[str] = None,
        status: typing.Optional[CollectionActionStatusEnum] = None,
        action_type: typing.Optional[CollectionActionTypeEnum] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseCollectionActionLogResponse:
        """
        Retrieve collection action logs for your partner account. Supports filtering by client, loan, installment, status, or action type.

        Parameters
        ----------
        client_id : typing.Optional[str]

        loan_id : typing.Optional[str]

        installment_id : typing.Optional[str]

        status : typing.Optional[CollectionActionStatusEnum]

        action_type : typing.Optional[CollectionActionTypeEnum]

        page : typing.Optional[int]

        page_size : typing.Optional[int]

        order_by : typing.Optional[str]
            Field to order the results by, e.g., 'created_at:desc,updated_at:asc'

        q : typing.Optional[str]
            Query string for filtering. Format: "field:operator:value;...". Supported fields: id, collection_action_id, action_type, status, client_id, loan_id, installment_id, scheduled_for. Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseCollectionActionLogResponse
            Successful Response

        Examples
        --------
        from voltaria import Voltaria

        client = Voltaria(
            api_key="YOUR_API_KEY",
        )
        client.collections.list_collection_action_logs()
        """
        _response = self._raw_client.list_collection_action_logs(
            client_id=client_id,
            loan_id=loan_id,
            installment_id=installment_id,
            status=status,
            action_type=action_type,
            page=page,
            page_size=page_size,
            order_by=order_by,
            q=q,
            request_options=request_options,
        )
        return _response.data

    def update_collection_action_log(
        self,
        log_id: str,
        *,
        status: CollectionActionLogUpdatePayloadStatus,
        notes: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CollectionActionLogResponse:
        """
        Update the status and notes of a collection action log.

        Parameters
        ----------
        log_id : str

        status : CollectionActionLogUpdatePayloadStatus
            The updated status of the action: 'completed' or 'failed'

        notes : typing.Optional[str]
            Notes about this action

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CollectionActionLogResponse
            Successful Response

        Examples
        --------
        from voltaria import Voltaria

        client = Voltaria(
            api_key="YOUR_API_KEY",
        )
        client.collections.update_collection_action_log(
            log_id="log_id",
            status="completed",
        )
        """
        _response = self._raw_client.update_collection_action_log(
            log_id, status=status, notes=notes, request_options=request_options
        )
        return _response.data


class AsyncCollectionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCollectionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCollectionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCollectionsClient
        """
        return self._raw_client

    async def list_collection_actions(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseCollectionActionResponse:
        """
        Retrieve all collection actions configured for your partner account.

        Parameters
        ----------
        page : typing.Optional[int]

        page_size : typing.Optional[int]

        order_by : typing.Optional[str]
            Field to order the results by, e.g., 'created_at:desc,updated_at:asc'

        q : typing.Optional[str]
            Query string for filtering. Format: "field:operator:value;...". Supported fields: id, name, action_type, is_active, timing. Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseCollectionActionResponse
            Successful Response

        Examples
        --------
        import asyncio

        from voltaria import AsyncVoltaria

        client = AsyncVoltaria(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.collections.list_collection_actions()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_collection_actions(
            page=page, page_size=page_size, order_by=order_by, q=q, request_options=request_options
        )
        return _response.data

    async def list_collection_action_logs(
        self,
        *,
        client_id: typing.Optional[str] = None,
        loan_id: typing.Optional[str] = None,
        installment_id: typing.Optional[str] = None,
        status: typing.Optional[CollectionActionStatusEnum] = None,
        action_type: typing.Optional[CollectionActionTypeEnum] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseCollectionActionLogResponse:
        """
        Retrieve collection action logs for your partner account. Supports filtering by client, loan, installment, status, or action type.

        Parameters
        ----------
        client_id : typing.Optional[str]

        loan_id : typing.Optional[str]

        installment_id : typing.Optional[str]

        status : typing.Optional[CollectionActionStatusEnum]

        action_type : typing.Optional[CollectionActionTypeEnum]

        page : typing.Optional[int]

        page_size : typing.Optional[int]

        order_by : typing.Optional[str]
            Field to order the results by, e.g., 'created_at:desc,updated_at:asc'

        q : typing.Optional[str]
            Query string for filtering. Format: "field:operator:value;...". Supported fields: id, collection_action_id, action_type, status, client_id, loan_id, installment_id, scheduled_for. Supported operators: is, in, not_in, contains, not_contains, like, not_like, ilike, not_ilike, gt, gte, lt, lte, starts_with, ends_with, is_null, is_not_null.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseCollectionActionLogResponse
            Successful Response

        Examples
        --------
        import asyncio

        from voltaria import AsyncVoltaria

        client = AsyncVoltaria(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.collections.list_collection_action_logs()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_collection_action_logs(
            client_id=client_id,
            loan_id=loan_id,
            installment_id=installment_id,
            status=status,
            action_type=action_type,
            page=page,
            page_size=page_size,
            order_by=order_by,
            q=q,
            request_options=request_options,
        )
        return _response.data

    async def update_collection_action_log(
        self,
        log_id: str,
        *,
        status: CollectionActionLogUpdatePayloadStatus,
        notes: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CollectionActionLogResponse:
        """
        Update the status and notes of a collection action log.

        Parameters
        ----------
        log_id : str

        status : CollectionActionLogUpdatePayloadStatus
            The updated status of the action: 'completed' or 'failed'

        notes : typing.Optional[str]
            Notes about this action

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CollectionActionLogResponse
            Successful Response

        Examples
        --------
        import asyncio

        from voltaria import AsyncVoltaria

        client = AsyncVoltaria(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.collections.update_collection_action_log(
                log_id="log_id",
                status="completed",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_collection_action_log(
            log_id, status=status, notes=notes, request_options=request_options
        )
        return _response.data
