# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .currency_enum import CurrencyEnum


class AvailableFunding(UniversalBaseModel):
    currency: CurrencyEnum = pydantic.Field()
    """
    Currency of the limit
    """

    limit: str
    later: typing.Optional[str] = None
    max_maturity_days: int
    rate: str
    outstanding: str
    available: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
