# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bulk_repayment_result import BulkRepaymentResult


class BulkRepaymentTaskStatus(UniversalBaseModel):
    task_id: str = pydantic.Field()
    """
    Task ID
    """

    status: str = pydantic.Field()
    """
    Task status
    """

    current: typing.Optional[int] = pydantic.Field(default=None)
    """
    Current progress count
    """

    total: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total items to process
    """

    result: typing.Optional[BulkRepaymentResult] = pydantic.Field(default=None)
    """
    Final result when task is completed
    """

    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Error message if task failed
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
