# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .checklist_type_enum import ChecklistTypeEnum


class ChecklistSummaryPartnerResponse(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique checklist summary identifier.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    When the summary was generated.
    """

    type: ChecklistTypeEnum = pydantic.Field()
    """
    Checklist type.
    """

    ai_description: typing.Optional[str] = pydantic.Field(default=None)
    """
    AI-generated summary of the checklist.
    """

    total_items: int = pydantic.Field()
    """
    Total number of checklist items.
    """

    completed_items: int = pydantic.Field()
    """
    Number of completed checklist items.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
