# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .client_limit_response import ClientLimitResponse
from .client_status_enum import ClientStatusEnum
from .client_type_enum import ClientTypeEnum
from .jurisdiction_enum import JurisdictionEnum


class ClientResponse(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The ID of the client
    """

    created_at: dt.datetime = pydantic.Field()
    """
    The creation date of the client
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    The last update date of the client
    """

    correlation_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The correlation ID you provided at the creation of the client
    """

    name: str = pydantic.Field()
    """
    The name of the client
    """

    type: ClientTypeEnum = pydantic.Field()
    """
    The type of the client, must be one of `individual`, `corporate`
    """

    jurisdiction: JurisdictionEnum = pydantic.Field()
    """
    The jurisdiction of the client, must be one of `eu`, `us`, `uk`
    """

    company_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    The company number of the client if type is `corporate`
    """

    status: ClientStatusEnum = pydantic.Field()
    """
    The status of the client. One of the following: `active, rejected, deactivated, pending, pending_onboarding, pre_approved, deleted, inactive`
    """

    limits: typing.Optional[typing.List[ClientLimitResponse]] = pydantic.Field(default=None)
    """
    The limits associated with the client
    """

    data: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Additional data associated with the client
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
