# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ClientDataResponse(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The unique identifier for the client data entry
    """

    created_at: dt.datetime = pydantic.Field()
    """
    The timestamp when the client data entry was created
    """

    client_id: str = pydantic.Field()
    """
    The unique identifier for the client associated with the data
    """

    data: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    The actual data associated with the client
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
