# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .client_user_status_enum import ClientUserStatusEnum
from .kyc_status_enum import KycStatusEnum
from .role_response import RoleResponse


class ClientUserResponse(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique client user identifier.
    """

    partner_id: str = pydantic.Field()
    """
    ID of the partner this user belongs to.
    """

    client_id: str = pydantic.Field()
    """
    ID of the client this user belongs to.
    """

    email: str = pydantic.Field()
    """
    Email address of the portal user.
    """

    role_id: str = pydantic.Field()
    """
    ID of the role assigned to the user.
    """

    role: typing.Optional[RoleResponse] = pydantic.Field(default=None)
    """
    Role assigned to the user.
    """

    status: ClientUserStatusEnum = pydantic.Field()
    """
    Account status. One of: `pending`, `active`, `inactive`.
    """

    is_email_verified: bool = pydantic.Field()
    """
    Whether the user has verified their email address.
    """

    kyc_status: KycStatusEnum = pydantic.Field()
    """
    KYC verification status of the user.
    """

    first_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    First name of the user.
    """

    last_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Last name of the user.
    """

    phone: typing.Optional[str] = pydantic.Field(default=None)
    """
    Phone number of the user.
    """

    is2fa_enabled: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="is_2fa_enabled"),
        pydantic.Field(
            alias="is_2fa_enabled", description="Whether two-factor authentication is enabled for this user."
        ),
    ] = None
    is2fa_required: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="is_2fa_required"),
        pydantic.Field(
            alias="is_2fa_required", description="Whether two-factor authentication is required for this user."
        ),
    ] = None
    created_at: dt.datetime = pydantic.Field()
    """
    Timestamp when the user was created.
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    Timestamp when the user was last updated.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
