# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .collection_action_type_enum import CollectionActionTypeEnum


class CollectionActionResponse(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The ID of the collection action
    """

    name: str = pydantic.Field()
    """
    The name of the collection action
    """

    action_type: CollectionActionTypeEnum = pydantic.Field()
    """
    The channel used for this action
    """

    is_active: bool = pydantic.Field()
    """
    Whether this action is currently active
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    A description of the collection action
    """

    timing: str = pydantic.Field()
    """
    Timing offset relative to the installment due date, e.g. 'd-5' (5 days before) or 'd+3' (3 days after)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
