# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .collection_action_status_enum import CollectionActionStatusEnum
from .collection_action_type_enum import CollectionActionTypeEnum


class CollectionActionLogResponse(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The ID of the collection action log
    """

    collection_action_id: str = pydantic.Field()
    """
    The ID of the collection action this log belongs to
    """

    action_type: CollectionActionTypeEnum = pydantic.Field()
    """
    The channel used for this action
    """

    action_name: str = pydantic.Field()
    """
    The name of the action at the time it was triggered
    """

    status: CollectionActionStatusEnum = pydantic.Field()
    """
    The current status of the action
    """

    client_id: str = pydantic.Field()
    """
    The ID of the client this action targets
    """

    loan_id: str = pydantic.Field()
    """
    The ID of the loan this action targets
    """

    installment_id: str = pydantic.Field()
    """
    The ID of the installment this action targets
    """

    flag: bool = pydantic.Field()
    """
    Whether this action needs manual follow-up
    """

    notes: typing.Optional[str] = pydantic.Field(default=None)
    """
    Notes about this action
    """

    scheduled_for: dt.datetime = pydantic.Field()
    """
    When this action is/was scheduled to run
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
