# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CurrencyFieldSpec(UniversalBaseModel):
    required: typing.List[str] = pydantic.Field()
    """
    Fields that must be provided for this currency.
    """

    optional: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Fields that are accepted but not required.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
