# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DocumentResponse(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The ID of the document
    """

    category: str = pydantic.Field()
    """
    The category of the document (kyc, financial, etc.)
    """

    file_name: str = pydantic.Field()
    """
    The name of the uploaded file
    """

    file_type: str = pydantic.Field()
    """
    The content type of the file
    """

    client_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The associated client ID
    """

    file_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The Presigned URL of the file. This is a temporary URL that allows you to download the file.
    """

    loan_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the associated loan, if applicable
    """

    installment_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the associated installment, if applicable
    """

    folder_path: typing.Optional[str] = pydantic.Field(default=None)
    """
    Slash-delimited folder path used to organise the document, e.g. 'Legal/Contracts'. Null means the document is unfiled (at the root).
    """

    document_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Optional document date (e.g. the date an investment document was issued)
    """

    expiry_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Optional expiry date of the document
    """

    distribution_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the associated distribution (coupon), if applicable
    """

    created_at: dt.datetime = pydantic.Field()
    """
    The date and time when the document was created
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
