# This file was auto-generated by Fern from our API Definition.

import typing

InstallmentStatusEnum = typing.Union[
    typing.Literal["active", "overdue", "default", "sold", "restructured", "repaid", "pending", "deleted", "inactive"],
    typing.Any,
]
