# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .client_base_info import ClientBaseInfo
from .currency_enum import CurrencyEnum
from .installment_status_enum import InstallmentStatusEnum


class InstallmentResponseWithClientInfo(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The ID of the installment
    """

    created_at: dt.datetime = pydantic.Field()
    """
    The creation date of the installment
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    The last update date of the installment
    """

    partner_id: str = pydantic.Field()
    """
    The partner ID
    """

    client_id: str = pydantic.Field()
    """
    The client ID
    """

    currency: CurrencyEnum = pydantic.Field()
    """
    The currency of the installment
    """

    status: InstallmentStatusEnum = pydantic.Field()
    """
    The status of the installment (possible values: active, overdue, default, sold, restructured, repaid, pending)
    """

    loan_id: str = pydantic.Field()
    """
    The associated loan ID
    """

    amount: str = pydantic.Field()
    """
    The total amount of the installment
    """

    expected_repayment_at: dt.datetime = pydantic.Field()
    """
    The expected repayment date
    """

    installment_number: int = pydantic.Field()
    """
    The installment number in sequence
    """

    installments: int = pydantic.Field()
    """
    The total number of installments
    """

    principal: str = pydantic.Field()
    """
    The principal amount of the installment
    """

    interest: str = pydantic.Field()
    """
    The interest amount of the installment
    """

    repayment_amount: typing.Optional[str] = pydantic.Field(default=None)
    """
    The amount repaid so far for this installment
    """

    repayment_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The actual repayment date
    """

    client: typing.Optional[ClientBaseInfo] = pydantic.Field(default=None)
    """
    The client details associated with the installment
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
