# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .limit_request_source_enum import LimitRequestSourceEnum
from .limit_request_status_enum import LimitRequestStatusEnum


class LimitRequestResponse(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The ID of the limit request
    """

    client_id: str = pydantic.Field()
    """
    The ID of the client associated with the limit request
    """

    status: LimitRequestStatusEnum = pydantic.Field()
    """
    The status of the limit request. One of the following: pending, approved, rejected
    """

    requested_limit: str = pydantic.Field()
    """
    The requested limit amount
    """

    reason: str = pydantic.Field()
    """
    The reason for the limit request
    """

    response: typing.Optional[str] = pydantic.Field(default=None)
    """
    The response to the limit request
    """

    waiver_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the waiver associated with this limit request
    """

    source: LimitRequestSourceEnum = pydantic.Field()
    """
    The origin of the request. 'partner' indicates the request was submitted by your account; 'internal' indicates it was initiated by Winyield on your behalf.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    The timestamp when the limit request was created
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
