# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .client_base_info import ClientBaseInfo
from .currency_enum import CurrencyEnum
from .loan_payment_status_enum import LoanPaymentStatusEnum
from .loan_status_enum import LoanStatusEnum


class LoanResponseWithClientInfo(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The ID of the loan
    """

    created_at: dt.datetime = pydantic.Field()
    """
    The creation date of the loan
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    The last update date of the loan
    """

    partner_id: str = pydantic.Field()
    """
    The ID of the partner
    """

    client_id: str = pydantic.Field()
    """
    The ID of the client
    """

    currency: CurrencyEnum = pydantic.Field()
    """
    The currency of the loan
    """

    amount: str = pydantic.Field()
    """
    The amount of the loan
    """

    status: LoanStatusEnum = pydantic.Field()
    """
    The status of the loan
    """

    irr: typing.Optional[str] = pydantic.Field(default=None)
    """
    The internal rate of return
    """

    loan_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    The date of the loan
    """

    currency_rate: str = pydantic.Field()
    """
    The currency rate conversion to EUR at the time of the loan
    """

    correlation_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The correlation ID provided at the creation of the loan
    """

    payment_status: typing.Optional[LoanPaymentStatusEnum] = pydantic.Field(default=None)
    """
    The payment status of the loan
    """

    payment_reference: typing.Optional[str] = pydantic.Field(default=None)
    """
    The payment reference for the loan
    """

    early_settlement_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    The date of early settlement if the loan was settled early
    """

    early_settlement_amount: typing.Optional[str] = pydantic.Field(default=None)
    """
    The settlement amount at early settlement if applicable
    """

    data: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Additional data related to the loan
    """

    client: ClientBaseInfo = pydantic.Field()
    """
    The client details associated with the loan
    """

    outstanding_principal: typing.Optional[str] = pydantic.Field(default=None)
    """
    Remaining principal for installments with status active or overdue, net of any repayments already made
    """

    remaining_amount: typing.Optional[str] = pydantic.Field(default=None)
    """
    Remaining amount (principal and interest) for installments with status active or overdue, net of any repayments already made
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
