# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .loan_review_request_status_enum import LoanReviewRequestStatusEnum


class LoanReviewRequestResponse(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The ID of the loan review request
    """

    loan_id: str = pydantic.Field()
    """
    The ID of the loan associated with the review request
    """

    client_id: str = pydantic.Field()
    """
    The ID of the client associated with the review request
    """

    status: LoanReviewRequestStatusEnum = pydantic.Field()
    """
    The status of the review request. One of the following: pending, approved, rejected
    """

    notes: typing.Optional[str] = pydantic.Field(default=None)
    """
    The requester's note for the review request
    """

    response: typing.Optional[str] = pydantic.Field(default=None)
    """
    The reviewer's note explaining the approval or rejection
    """

    reviewed_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The timestamp when the review request was approved or rejected
    """

    created_at: dt.datetime = pydantic.Field()
    """
    The timestamp when the review request was created
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    The timestamp when the review request was last updated
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
