# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class NoteResponse(UniversalBaseModel):
    """
    A note, with the name and email of whoever wrote it.
    """

    id: str = pydantic.Field()
    """
    Note ID.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    When the note was created.
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    When the note was last updated.
    """

    content: str = pydantic.Field()
    """
    The note content.
    """

    loan_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Related loan ID, if applicable.
    """

    installment_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Related installment ID, if applicable.
    """

    author_first_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    First name of the note author.
    """

    author_last_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Last name of the note author.
    """

    author_email: typing.Optional[str] = pydantic.Field(default=None)
    """
    Email of the note author. Null if the author was deleted.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
