# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .payment_promise_status_enum import PaymentPromiseStatusEnum


class PaymentPromiseResponse(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The ID of the payment promise
    """

    created_at: dt.datetime = pydantic.Field()
    """
    When the promise was created
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    When the promise was last updated
    """

    installment_id: str = pydantic.Field()
    """
    The ID of the installment this promise relates to
    """

    partner_id: str = pydantic.Field()
    """
    The ID of the partner the installment belongs to
    """

    client_id: str = pydantic.Field()
    """
    The ID of the client the installment belongs to
    """

    loan_id: str = pydantic.Field()
    """
    The ID of the loan the installment belongs to
    """

    amount: str = pydantic.Field()
    """
    The amount the client has promised to pay
    """

    promised_date: dt.date = pydantic.Field()
    """
    The date the client has committed to pay by
    """

    status: PaymentPromiseStatusEnum = pydantic.Field()
    """
    The status of the promise
    """

    notes: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional notes captured during the collections interaction
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
