# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .task_public_actor_type_enum import TaskPublicActorTypeEnum
from .task_status_enum import TaskStatusEnum


class TaskPartnerStatusHistoryResponse(UniversalBaseModel):
    """
    One status change on a task: when it happened, what it moved from and to, and
    who made it.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    When the status changed.
    """

    old_status: typing.Optional[TaskStatusEnum] = pydantic.Field(default=None)
    """
    The status before the change.
    """

    new_status: TaskStatusEnum = pydantic.Field()
    """
    The status after the change.
    """

    actor_type: TaskPublicActorTypeEnum = pydantic.Field()
    """
    Who made the change. One of the following: partner, support
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
