# Hand-written package entry — NOT generated by Fern.
#
# Re-exports the full generated surface from the `_generated` subpackage, then
# overrides the public client classes with the prefix-routing wrapper. Because
# `from ._generated import *` is dynamic, new models/enums/resources added to
# the API show up here automatically on the next `fern generate` — nothing here
# needs hand-editing when the API grows.

from ._generated import *  # noqa: F401, F403
from ._wrapper import AsyncVoltaria, InvalidApiKeyError, Voltaria  # noqa: F401

# `Voltaria` / `AsyncVoltaria` above intentionally shadow the generated client
# classes pulled in by the star import, so `from voltaria import Voltaria`
# resolves to the prefix-routing wrapper.
